language: node_js

node_js:
  - '0.10'

before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-djangoproject' ]; then cd .. && eval "mv $currentfolder generator-djangoproject" && cd generator-djangoproject; fi

branches:
    only:
        - master
